### ISSUE TITLE
Extend the API guidelines with a concrete ruleset

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/Commonalities#15]
Several subprojects could be facing issues currently if API specification contributions are made without performing a linting check. To ensure that we can enable this process in Camara natively, we would need a concrete ruleset to validate the spec files against. This issue is created to propose an extension to the existing guidelines by adding a concrete ruleset.

An example of a subproject requesting such a check can be seen here https://github.com/camaraproject/QualityOnDemand/issues/158

**Comment by jlurien** [comment]
I don't have experience with any of Spectral or Megalinter, but seems to be some degree of compatibility between both: https://megalinter.io/latest/descriptors/openapi_spectral/, and Megalinter supports a ruleset defined in Spectral. We may agree on using the ruleset of Spectral if it is more convenient for OAS lintering, and then see which is the best way to integrate it with the Github CI

**Comment by RandyLevensalor** [comment]
Apologies for the delayed response.  I'm traveling this week and won't be able to join the commonalities call.

@jlurien pointed out correctly that Megalinter can be used to run Spectral and other linting tools.

I personally find Megalinter handy, since it not only provides support for other linters within the same GitHub actions, it all takes care of reporting errors.  This could be a project by project decision on how they choose to use spectral, assuming we use spectral.

I would advocate for using Spectral for this and begin developing rules in the commonalities repo.  There are some basic rules around Open API 3.0 that can be added fairly easily.  Some of the guidelines are a bit ambiguous when trying to define them in with a strict schema and it would be useful to clarify the this ambiguity as we write the rules.

**Comment by hdamker** [comment]
I'm also in favor of using mega linter as frame around other linting tools. In QualityOnDemand we have for example also integrated also JAVA linting for the test case implementation within the repository. Markdown linting could be another step (currently disabled within QoD).

I wouldn't recommend a project by project decision, rather we should establish a "central" support for establish the Github actions within the sub projects.

And yes, agree to use spectral linting for the specific rules in CAMARA according to the guidelines.

**Comment by Kevsy** [comment]
> rather we should establish a "central" support for establish the Github actions within the sub projects.

Indeed - [governance #95](https://github.com/camaraproject/Governance/issues/95) proposes that.

**Comment by rartych** [comment]
@Kevsy  @rkandoi  @ravindrapalaskar17 @shilpa-padgaonkar  Draft PR opened for further discussion

**Comment by rartych** [comment]
@RandyLevensalor My observation from trying Gihub action defined in PR https://github.com/camaraproject/Commonalities/pull/110 is that Megalinter report does not include "warning" information when there is no error detected by given linter.
As we have Spectral rules (from Spectral core set and CAMARA specific) producing warnings they are not reported when all problems with "error" severity are solved. I haven't found if it can be configured within Megalinter - it rather gives green light with no error and red light with at least one error detected.
There is also issue raised by @Kevsy https://github.com/camaraproject/Commonalities/issues/76 about linting responses severity.
Some rules does not indicate errors, but potential improvement or simplification of API specification - so the warning is the right severity level. Spectral allows also to produce "info" and "hint" responses.
