### ISSUE TITLE
How to inform API consumer about unprocessable subscription request in Async mode

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/Commonalities#243]
**Problem description**
In our subscription model we offer possibility for server to handle it synchronously or asynchronously.

Suppose we have a subscription request that the server is not able to handle (the monitoring area is not within operator area, the reachability status could ne follow this specific number, etc...) and the subscription server handles it in **async** mode.

How to inform the subscription requester that the request in not processable when server manages it in asynchronously ?

(in sync mode we do not have issue as we send back a 4xx error)

**Possible evolution**

- add another TerminationReason value: `SUBSCRIPTION_UNPROCESSABLE`
- add `terminationReasonComment` attibute to allow server to provide explantation 

**Alternative solution**

**Additional context**
cc: @PedroDiez & @shilpa-padgaonkar @akoshunyadi

**Comment by PedroDiez** [comment]
I understand this would be the case where, being a Telco Operator behaving in async mode, the processing of the subscriptionDetail information is happening after providing a subcriptionId.

So as, if GET /subscription would be queried, the "status" of the subscriptionId would be "ACTIVATION_REQUESTED" and after the processing is done and realized cannot be managed, the new proposed eventTermination Reason is returned back: SUBSCRIPTION_UNPROCESSABLE. 

Regarding the final "status" of this kind of subscriptions, I think the best approach is not kept as "DELETED" and effectively removed them "as they never existed" because it adds no historical value a subscription that would never be working (just thinking in loud).

In principle makes sense to me and I am checking in parallel internally with our team

**Comment by maxl2287** [comment]
@PedroDiez did you already have time to check this internally with your team?

**Comment by rartych** [comment]
It occured that we have optional property in event-subscription-template.yaml :

https://github.com/camaraproject/Commonalities/blob/9233f834c9cfb44dbb843ca72f22085f8559d4da/artifacts/camara-cloudevents/event-subscription-template.yaml#L629-L630

Currently it is not used in subscription APIs and missing `description` attribute.

**Comment by maxl2287** [comment]
@rartych From DeviceLocation side we aggree on using the `terminationDescription`. ✅ 
The second proposal from @bigludo7 was to add the `terminationReason` `SUBSCRIPTION_UNPROCESSABLE`.

Can we also align on that?

cc @PedroDiez @shilpa-padgaonkar @jlurien

**Comment by maxl2287** [comment]
> @rartych From DeviceLocation side we aggree on using the `terminationDescription`. ✅ The second proposal from @bigludo7 was to add the `terminationReason` `SUBSCRIPTION_UNPROCESSABLE`.
> 
> Can we also align on that?
> 
> cc @PedroDiez @shilpa-padgaonkar @jlurien

@rartych or @PedroDiez again requesting if we could align on `terminationReason` `SUBSCRIPTION_UNPROCESSABLE`?

**Comment by PedroDiez** [comment]
> > @rartych From DeviceLocation side we aggree on using the `terminationDescription`. ✅ The second proposal from @bigludo7 was to add the `terminationReason` `SUBSCRIPTION_UNPROCESSABLE`.
> > Can we also align on that?
> > cc @PedroDiez @shilpa-padgaonkar @jlurien
> 
> @rartych or @PedroDiez again requesting if we could align on `terminationReason` `SUBSCRIPTION_UNPROCESSABLE`?

I think we can align on that and set formally in MetaRelease Spring 25. Ok with the decsision taken in Device Location

**Comment by shilpa-padgaonkar** [comment]
@maxl2287 @PedroDiez @bigludo7  Fine for me to agree on terminationReason and SUBSCRIPTION_UNPROCESSABLE
