### ISSUE TITLE
Commonalities release 

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/Commonalities#32]
**Problem description**
As we have now moved all the commonalities deliverables to this new repo, we need to start planning for the release. 

Some points we need to discuss and agree to go ahead:

- Release number: Is v0.1.0 fine to start with? Any other preferences?
- Considering the kind of artifacts in Commonalities, release branch wouldn't be needed. Tag and release should be sufficient. Does anyone see a need for a release branch?
- Any urgent issues, pull requests we want to get through as a part of this release?
- Depending on the above point, we need to agree on the release date.

**Expected action**
Feedback on the above points & any other points I might have missed w.r.t release prep, would be helpful so that we can try to get a consensus in the upcoming commonalities call. 

**Additional context**

**Comment by shilpa-padgaonkar** [comment]
Do we individually version all commonalities document deliverables? - No better to use them as a group
No individual versioning of documents.
What does the version number mean?
- Major version indicates breaking changes for subprojects 
- Patch version is irrelevant.

**Comment by murthygorty** [comment]
My request is to release the first version of design guidelines without all the TMF references - I have several comments to make and the TMF reference is confusing in my opinion for Camara API Provider developers. We used to have an earlier version of the guidelines that is simpler to consume and conform to.
Once we have that release, we can review the contents around TMF and release the next version.

**Comment by hdamker** [comment]
Just for my (and maybe others) convenience here with the links generated by Github:

> PRs that will be merged before release:
> #35 , #33, #23 
> 
> Issues which can be closed with minor PRs before release:
> #5, #9 

@murthygorty to which PR/Issue do you refer (which introduces the TMF reference)?

**Comment by murthygorty** [comment]
Thanks for the comments @hdamker. I went back and looked for the version of the guidelines I'm thinking of - in the original location under WG and as far back as I could go ([link](Commonalities/documentation/Working/API-design-guidelines.md)) I still couldn't find the version I have in mind. Not sure what I was thinking of :-(

What I had in mind was the guidelines version without some of the sections in apification principles without domain-driven designs etc.

Since I cant point to the specific version, I suggest that we simply go ahead and ignore my comment. I can go ahead and open a new issue with my concerns around sections 2.1 and 2.3.
what do you think?
cc: @gmuratk
