### ISSUE TITLE
Mandatory Response Headers

### ISSUE THREAD

**Issue by sachinvodafone** [camaraproject/Commonalities#77]
I would like to confirm if we have explicitly defined certain response headers as mandatory, which must be present in each API response and that can be validated during our [OpenAPI Specification (OAS) spectral validation ](https://github.com/camaraproject/Commonalities/blob/a41b82d198afffd1053def40e7ec1be847b2be71/documentation/Linting-rules.md#1-spectral-core-ruleset)that we are in the process of defining. I have reviewed the [API documentation](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md), but I couldn't find any mention of mandatory response headers.

**Comment by eric-murray** [comment]
From the [Design Guidelines](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md)

> To avoid cluttering the CAMARA OAS (Swagger) definition files, the above headers must not be included explicitly in the API definition files even when supported, as it can be assumed that developers will already be familiar with their use.

So it is expected that developers will generally understand which of the standard headers to expect in the response and how to treat them. Several of these are mandatory because of HTTP specifications, not CAMARA specifications. Only "non-standard" headers whose existence somehow affects the use case need be documented, but this will be API dependent, and so will only be reflected in that specific API definition.

Headers "required" by a specific client implementation (for example, if they want to use a standard web browser) are not a concern for CAMARA, but rather for the specific API implementor, who can add the required headers to their own implementation. Providing additional response headers does not make the implementation "non-compliant".

**Comment by rartych** [comment]
Closed as agreed
