### ISSUE TITLE
Consolidation of minor changes needed in design guidelines for CloudEvents content

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/Commonalities#83]
**Problem description**
Certain minor points have been identified within the design guidelines that need to be changed for the CloudEvents content. This is a consolidation issue for the same. 

**Expected behavior**

**Alternative solution**

**Additional context**

**Comment by shilpa-padgaonkar** [comment]
@rartych  @bigludo7 Could you kindly document your findings under this issue?

**Comment by bigludo7** [comment]
@shilpa-padgaonkar 
As of now I have:

For instance-based subscription:
- For the POST subscriptions it is valid to provide async answer if the subscription is not created on the fly so response 201 & 202 must be present in the yaml in POST response (we have only 201 so far).
- We have a debate btw about the answer of a GET /subscriptions/{subscriptionId} when the subscription is not yet created - should be 404 or 202 ? I have not clear opinion on that wand feedback welcome.

For Notification:
- for the notification itself (not the subscription) we should have `application/cloudevents+json` instead of `application/json` for the `accept`. This point requires updating the example in the DG and probably adding a note. Rajat Kandoi highlighted that  cloudevents+json is not part of IANA registration but agreed that we can move forward.
- In the notification response we have a `data` attribute (type object) .  In this `data` we provide event notification details payload described in each CAMARA API and referenced by its `type`. As of now, this attribute is tagged as optional in the DG but in all 3 implementations I follow we shifted it to mandatory. Perhaps we will have an event not requiring additional information than the `type` (not use of `data` attribute), but probably we could indicate that sub project could shift this `data` to mandatory if required.

Please @rartych do not hesitate to jump it.

Shilpa I'm off tonight for the week so I will be able to updated the DG only next week.

**Comment by shilpa-padgaonkar** [comment]
> @shilpa-padgaonkar As of now I have:
> 
> For instance-based subscription:
> 
> * For the POST subscriptions it is valid to provide async answer if the subscription is not created on the fly so response 201 & 202 must be present in the yaml in POST response (we have only 201 so far).

Agree

> * We have a debate btw about the answer of a GET /subscriptions/{subscriptionId} when the subscription is not yet created - should be 404 or 202 ? I have not clear opinion on that wand feedback welcome.
> 
I would prefer 404. Shows the same in CloudEvents subscription.yaml

> For Notification:
> 
> * for the notification itself (not the subscription) we should have `application/cloudevents+json` instead of `application/json` for the `accept`. This point requires updating the example in the DG and probably adding a note. Rajat Kandoi highlighted that  cloudevents+json is not part of IANA registration but agreed that we can move forward.

Agree that we should have `application/cloudevents+json` 

> * In the notification response we have a `data` attribute (type object) .  In this `data` we provide event notification details payload described in each CAMARA API and referenced by its `type`. As of now, this attribute is tagged as optional in the DG but in all 3 implementations I follow we shifted it to mandatory. Perhaps we will have an event not requiring additional information than the `type` (not use of `data` attribute), but probably we could indicate that sub project could shift this `data` to mandatory if required.
> 
Agree, a simple note in design guidelines providing this hint should address this

> Please @rartych do not hesitate to jump it.
> 
> Shilpa I'm off tonight for the week so I will be able to updated the DG only next week.

**Comment by jlurien** [comment]
> > @shilpa-padgaonkar As of now I have:

> > * We have a debate btw about the answer of a GET /subscriptions/{subscriptionId} when the subscription is not yet created - should be 404 or 202 ? I have not clear opinion on that wand feedback welcome.
> 
> I would prefer 404. Shows the same in CloudEvents subscription.yaml

Agree. Either 404, or 200 if we had a subscription already created with some pending status

**Comment by rartych** [comment]
I have proposed changes in https://github.com/camaraproject/Commonalities/pull/86

> For Notification:
> 
>  * for the notification itself (not the subscription) we should have `application/cloudevents+json` instead of `application/json` for the `accept`. This point requires updating the example in the DG and probably adding a note. Rajat Kandoi highlighted that  cloudevents+json is not part of IANA registration but agreed that we can move forward.
> 
>  * In the notification response we have a `data` attribute (type object) .  In this `data` we provide event notification details payload described in each CAMARA API and referenced by its `type`. As of now, this attribute is tagged as optional in the DG but in all 3 implementations I follow we shifted it to mandatory. Perhaps we will have an event not requiring additional information than the `type` (not use of `data` attribute), but probably we could indicate that sub project could shift this `data` to mandatory if required.

I have also made some editorial changes.

@bigludo7  Unfortunately I cannot identify the content to be changed for these issues:
> For instance-based subscription:
> 
>  * For the POST subscriptions it is valid to provide async answer if the subscription is not created on the fly so response 201 & 202 must be present in the yaml in POST response (we have only 201 so far).
> 
>  * We have a debate btw about the answer of a GET /subscriptions/{subscriptionId} when the subscription is not yet created - should be 404 or 202 ? I have not clear opinion on that --> feedbacks welcome.
>

**Comment by bigludo7** [comment]
> @bigludo7 Unfortunately I cannot identify the content to be changed for these issues:
> 
> > For instance-based subscription:
> > 
> > * For the POST subscriptions it is valid to provide async answer if the subscription is not created on the fly so response 201 & 202 must be present in the yaml in POST response (we have only 201 so far).
> > * We have a debate btw about the answer of a GET /subscriptions/{subscriptionId} when the subscription is not yet created - should be 404 or 202 ? I have not clear opinion on that --> feedbacks welcome.

@rartych I was looking for a guidance about use of 202 and got it from @shilpa-padgaonkar and @jlurien. No need to update the guideline I think as we do not introduce specific 202 for GET answer. 
Thanks for the changes !

**Comment by PedroDiez** [comment]
Let me check this latest point. Think maybe we need to update the guideline within PR#86. I am commenting today

**Comment by bigludo7** [comment]
Thanks @PedroDiez 
So seems that we're all on same page: 404 if subscriptionId does not exist yet.

@rartych probably we can also consider https://github.com/camaraproject/Commonalities/issues/89 in this PR as we should not have too much debate. 
https://github.com/camaraproject/Commonalities/issues/90 will need additional discussion.

**Comment by PedroDiez** [comment]
And to be aligned, we would be also considering this below in [PR#86](https://github.com/camaraproject/Commonalities/pull/86) (I can include some considerations if it helps) 

1) One editorial Point: (remove 's' from subscriptionId)

Lines 1247, 1248
| GET | /subscriptions/{subscriptionId} | Operation to retrieve an event subscription |
| DELETE | /subscriptions/{subscriptionId} | Operation to delete an event subscription |

2) For the POST subscriptions it is valid to provide async answer if the subscription is not created on the fly so response 201 & 202 must be present in the yaml in POST response (we have only 201 so far).

Maybe it is worth to indicate in commonalities, Susbcription Creation/Deletion may be SYNC/ASYNC procedure therefore:

POST /subscriptions can have 201 (SYNC) or 202 (ASYNC) response, so as 201 & 202 must be present in the yaml in POST response
DELETE /subscriptions/{subscriptionId} can have 204 (SYNC) or 202 (ASYNC) response so as 204 & 202 must be present in the yaml in DELETE response

**Comment by rartych** [comment]
Thank you @PedroDiez, I have integrated point 1 in PR https://github.com/camaraproject/Commonalities/pull/86.

Regarding point 2 - we do not have precise requirements on SYNC/ASYNC operations in API Design Guidelines, only the table of [HTTP Response Codes](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#32-http-response-codes). 
Should we add specific requirements for Subscription Creation/Deletion?

**Comment by PedroDiez** [comment]
Thank you very much @rartych for integrating point 1 in [PR#86](https://github.com/camaraproject/Commonalities/pull/86).


Regarding Point 2. Get your point Rafal, In [HTTP Response Codes](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#32-http-response-codes) table it is mentioned in a generic way `It should apply to async processes.` (at least to me that is fine, because is the purpose of 202 Accepted response).

My question/doubt here, regarding the initial comment of the thread by Ludovic is if it is worth to indicate in section 12 of the guidelines that (something in this way)

_Susbcription Creation/Deletion may be SYNC/ASYNC procedure therefore:

POST /subscriptions can have 201 (SYNC) or 202 (ASYNC) response, so as 201 & 202 must be present in the yaml in POST response
DELETE /subscriptions/{subscriptionId} can have 204 (SYNC) or 202 (ASYNC) response so as 204 & 202 must be present in the yaml in DELETE response_

Or it is fine that in every API where subscriptions are managed, just to add 202 HTTP code to POST/DELETE actions. My concern regarding this is that this topic can generate discussions in different WGs, so as if this is clarified in Commonalities, it is a matter of alignment en every WG impacted.

WDYT @bigludo7 , @shilpa-padgaonkar?

**Comment by shilpa-padgaonkar** [comment]
@PedroDiez I agree that if some small description can save further discussions in several WGs, we can add a small description in the design guidelines as you have indicated.

**Comment by shilpa-padgaonkar** [comment]
@bigludo7 @rartych 
One other small point has come to my notice. In design guidelines in section 12.2, in the rules table for cloudevents model, under specversion we are only allowed to specify max and min version and not include the patch number. 

In the above generic description "CAMARA event notification leverages [CloudEvents](https://cloudevents.io/)" .... we must specify the cloudevents release number explicitly. For eg. CAMARA event notification leverages [CloudEvents](https://cloudevents.io/) and is based on release https://github.com/cloudevents/spec/releases/tag/v1.0.2

It would be great to have this change merged before we make the commonalities release. WDYT?

**Comment by bigludo7** [comment]
@PedroDiez @shilpa-padgaonkar @rartych 
Yes agreed with Shilpa - make sense to have the Cloud Event specification explicitly listed.  

For the async/sync with the notes added by Rafal under the operation table in 12.1 I'm fine.

Some food for thought for future update:  Cloud Event specification for delivery response here https://github.com/cloudevents/spec/blob/main/cloudevents/http-webhook.md#22-delivery-response and wondering if we should align (There are use of 410, 429, etc..) .... will open an issue to get feedback on this but **not** for this release.

**Comment by rartych** [comment]
CloudEvents version added in https://github.com/camaraproject/Commonalities/pull/86/commits/97f35ecc2df0494f1ec88fcc893e37dca9cc657f

@PedroDiez Do notes about sync/async added in https://github.com/camaraproject/Commonalities/pull/86/commits/8bcb964030e80a3086dd29dbe42e1db6dddf7b10 need to be extended?

**Comment by PedroDiez** [comment]
> CloudEvents version added in [97f35ec](https://github.com/camaraproject/Commonalities/commit/97f35ecc2df0494f1ec88fcc893e37dca9cc657f)
> 
> @PedroDiez Do notes about sync/async added in [8bcb964](https://github.com/camaraproject/Commonalities/commit/8bcb964030e80a3086dd29dbe42e1db6dddf7b10) need to be extended?

Notes regarding sync/async looks goot to me Rafal
